on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - "script/*"
      - "patches/*"
  workflow_dispatch:

env:
  version: m90-adbb69cd7f

jobs:

  macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: python3 script/check_release.py --version ${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: python3 script/checkout.py --version ${{ env.version }}
      - run: python3 script/build.py
      - run: python3 script/archive.py
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.version }}-macos-Release-x64.zip
          path: '*.zip'
      - run: python3 script/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo ./script/prepare_linux.sh
      - run: python3 script/check_release.py --version ${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/checkout.py --version ${{ env.version }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/build.py
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/archive.py
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.version }}-linux-Release-x64.zip
          path: '*.zip'
      - run: python3 script/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-gcc4:
    runs-on: ubuntu-latest
    container: ubuntu:14.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo ./script/prepare_linux.sh
      - run: sudo apt-get install binutils-2.26 -y
      - run: python3 script/check_release.py --version ${{ env.version }} --classifier gcc4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/checkout.py --version ${{ env.version }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/build.py
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/archive.py --classifier gcc4
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.version }}-linux-Release-x64-gcc4.zip
          path: '*.zip'
      - run: python3 script/release.py --classifier gcc4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  android:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        machine: [arm, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ls -l /usr/local/lib/android/sdk/ndk-bundle
      - run: sudo ./script/prepare_linux.sh
      - run: python3 script/check_release.py --version ${{ env.version }} --system android --machine ${{ matrix.machine }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/checkout.py --version ${{ env.version }} --system android --machine ${{ matrix.machine }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/build.py --system android --machine ${{ matrix.machine }} --ndk "/usr/local/lib/android/sdk/ndk-bundle"
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/archive.py --system android --machine ${{ matrix.machine }}
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.version }}-android-Release-${{ matrix.machine }}.zip
          path: '*.zip'
      - run: python3 script/release.py --system android --machine ${{ matrix.machine }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: python3 script/check_release.py --version ${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - shell: bash
        run: python3 script/checkout.py --version ${{ env.version }}
      - shell: bash
        run: python3 script/build.py
      - shell: bash
        run: python3 script/archive.py
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.version }}-windows-Release-x64.zip
          path: '*.zip'
      - shell: bash
        run: python3 script/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
